/*
 * This file was automatically generated.
 */
namespace Worldline.Acquiring.Sdk.V1.Domain
{
    public class ApiActionResponseForRefund
    {
        /// <summary>
        /// A globally unique identifier of the operation, generated by you.<br />
        /// We advise you to submit a UUID or an identifier composed of an arbitrary string
        /// and a UUID/URL-safe Base64 UUID (RFC 4648 §5).<br />
        /// It's used to detect duplicate requests or to reference an operation in
        /// technical reversals.
        /// </summary>
        public string OperationId { get; set; }

        /// <summary>
        /// A summary of the refund used for responses
        /// </summary>
        public ApiRefundSummaryForResponse Refund { get; set; }

        /// <summary>
        /// The party that originated the response
        /// </summary>
        public string Responder { get; set; }

        /// <summary>
        /// Numeric response code, e.g. 0000, 0005
        /// </summary>
        public string ResponseCode { get; set; }

        /// <summary>
        /// Category of response code.
        /// </summary>
        public string ResponseCodeCategory { get; set; }

        /// <summary>
        /// Description of the response code
        /// </summary>
        public string ResponseCodeDescription { get; set; }
    }
}
