/*
 * This file was automatically generated.
 */
using System;

namespace Worldline.Acquiring.Sdk.V1.Domain
{
    public class ApiCaptureRequest
    {
        /// <summary>
        /// Amount to capture. If not provided, the full amount will be captured.
        /// </summary>
        public AmountData Amount { get; set; }

        /// <summary>
        /// Additional data regarding the breakdown of the capture amount. This can include amounts such as tip.
        /// The amounts specified are included in the total capture <c>amount</c>, the information is provided
        /// for data enrichment and reconciliation purposes.
        /// </summary>
        public CaptureAmountBreakdownData CaptureAmountBreakdownData { get; set; }

        /// <summary>
        /// The index of the partial capture. Not needed for full capture.
        /// </summary>
        public int? CaptureSequenceNumber { get; set; }

        /// <summary>
        /// Dynamic Currency Conversion (DCC) rate data from DCC lookup response.<br />
        /// Mandatory for DCC transactions.
        /// </summary>
        public DccData DynamicCurrencyConversion { get; set; }

        /// <summary>
        /// Indicates whether this partial capture is the final one.<br />
        /// Not needed for full capture.
        /// </summary>
        public bool? IsFinal { get; set; }

        /// <summary>
        /// Additional data for marketplace transactions. Required when capturing VISA payments on behalf of
        /// sellers that are located in a different region than the marketplace. We advise marketplaces to
        /// always provide this data to ensure optimal processing of the transactions.
        /// </summary>
        public MarketplaceData MarketplaceData { get; set; }

        /// <summary>
        /// A globally unique identifier of the operation, generated by you.<br />
        /// We advise you to submit a UUID or an identifier composed of an arbitrary string
        /// and a UUID/URL-safe Base64 UUID (RFC 4648 §5).<br />
        /// It's used to detect duplicate requests or to reference an operation in
        /// technical reversals.
        /// </summary>
        public string OperationId { get; set; }

        /// <summary>
        /// Payment References
        /// </summary>
        public PaymentReferences References { get; set; }

        public TerminalData TerminalData { get; set; }

        /// <summary>
        /// Timestamp of transaction in ISO 8601 format (YYYY-MM-DDThh:mm:ss+TZD)<br />
        /// It can be expressed in merchant time zone (ex: 2023-10-10T08:00+02:00)
        /// or in UTC (ex: 2023-10-10T08:00Z)
        /// </summary>
        public DateTimeOffset TransactionTimestamp { get; set; }
    }
}
