/*
 * This file was automatically generated.
 */
using System;

namespace Worldline.Acquiring.Sdk.V1.Domain
{
    public class ApiPaymentReversalRequest
    {
        /// <summary>
        /// Dynamic Currency Conversion (DCC) rate data from DCC lookup response.<br />
        /// Mandatory for DCC transactions.
        /// </summary>
        public DccData DynamicCurrencyConversion { get; set; }

        /// <summary>
        /// A globally unique identifier of the operation, generated by you.<br />
        /// We advise you to submit a UUID or an identifier composed of an arbitrary string
        /// and a UUID/URL-safe Base64 UUID (RFC 4648 §5).<br />
        /// It's used to detect duplicate requests or to reference an operation in
        /// technical reversals.
        /// </summary>
        public string OperationId { get; set; }

        /// <summary>
        /// Amount to reverse. If not provided, the full amount will be reversed.
        /// </summary>
        public AmountData ReversalAmount { get; set; }

        /// <summary>
        /// Timestamp of transaction in ISO 8601 format (YYYY-MM-DDThh:mm:ss+TZD)<br />
        /// It can be expressed in merchant time zone (ex: 2023-10-10T08:00+02:00)
        /// or in UTC (ex: 2023-10-10T08:00Z)
        /// </summary>
        public DateTimeOffset TransactionTimestamp { get; set; }
    }
}
