/*
 * This file was automatically generated.
 */
namespace Worldline.Acquiring.Sdk.V1.Domain
{
    public class ApiReferencesForResponses
    {
        /// <summary>
        /// (PAR) Unique identifier associated with a specific cardholder PAN
        /// </summary>
        public string PaymentAccountReference { get; set; }

        /// <summary>
        /// Retrieval reference number (RRN) for transaction
        /// </summary>
        public string RetrievalReferenceNumber { get; set; }

        /// <summary>
        /// ID assigned by the scheme to identify a transaction through
        /// its whole lifecycle.
        /// </summary>
        public string SchemeTransactionId { get; set; }

        /// <summary>
        /// A unique transaction identifier generated by Mastercard to provide consistent
        /// linking of related transaction activity throughout the transaction lifecycle.
        /// </summary>
        public string SchemeTransactionLinkId { get; set; }
    }
}
