/*
 * This file was automatically generated.
 */
using System;
using System.Collections.Generic;

namespace Worldline.Acquiring.Sdk.V1.Domain
{
    public class ApiRefundResponse
    {
        /// <summary>
        /// Authorization approval code
        /// </summary>
        public string AuthorizationCode { get; set; }

        public CardPaymentDataForResource CardPaymentData { get; set; }

        /// <summary>
        /// EMV data of the card as tag/value pairs.
        /// It is needed when cardEntryMode is CHIP or CONTACTLESS.
        /// </summary>
        public IList<EmvDataItem> EmvData { get; set; }

        /// <summary>
        /// A globally unique identifier of the operation, generated by you.<br />
        /// We advise you to submit a UUID or an identifier composed of an arbitrary string
        /// and a UUID/URL-safe Base64 UUID (RFC 4648 §5).<br />
        /// It's used to detect duplicate requests or to reference an operation in
        /// technical reversals.
        /// </summary>
        public string OperationId { get; set; }

        /// <summary>
        /// The identifier of the payment referenced by this refund.
        /// </summary>
        public string ReferencedPaymentId { get; set; }

        /// <summary>
        /// A set of references returned in responses
        /// </summary>
        public ApiReferencesForResponses References { get; set; }

        /// <summary>
        /// the ID of the refund
        /// </summary>
        public string RefundId { get; set; }

        /// <summary>
        /// The party that originated the response
        /// Possible values are:
        /// <list type="bullet">
        ///   <item><description>WORLDLINE</description></item>
        ///   <item><description>ISSUER</description></item>
        ///   <item><description>SCHEME</description></item>
        ///   <item><description>PARTNER</description></item>
        /// </list>
        /// </summary>
        public string Responder { get; set; }

        /// <summary>
        /// Numeric response code, e.g. 0000, 0005
        /// </summary>
        public string ResponseCode { get; set; }

        /// <summary>
        /// Category of response code.<br />
        /// Possible values are:
        /// <list type="bullet">
        ///   <item><description>APPROVED</description></item>
        ///   <item><description>PARTIALLY_APPROVED</description></item>
        ///   <item><description>DECLINED</description></item>
        /// </list>
        /// </summary>
        public string ResponseCodeCategory { get; set; }

        /// <summary>
        /// Description of the response code
        /// </summary>
        public string ResponseCodeDescription { get; set; }

        /// <summary>
        /// The duration to wait after the initial submission before retrying the payment.<br />
        /// Expressed using ISO 8601 duration format, ex: PT2H for 2 hours.<br />
        /// This field is only present when the payment can be retried later.<br />
        /// PT0 means that the payment can be retried immediately.
        /// </summary>
        public string RetryAfter { get; set; }

        /// <summary>
        /// The status of the payment, refund or credit transfer<br />
        /// Possible values are:
        /// <list type="bullet">
        ///   <item><description>AUTHORIZED</description></item>
        ///   <item><description>NOT_AUTHORIZED</description></item>
        ///   <item><description>PENDING</description></item>
        ///   <item><description>PENDING_CAPTURE</description></item>
        ///   <item><description>CONFIRMED</description></item>
        ///   <item><description>REVERSED</description></item>
        ///   <item><description>CANCELLED</description></item>
        /// </list>
        /// </summary>
        public string Status { get; set; }

        /// <summary>
        /// Timestamp of the status in format yyyy-MM-ddTHH:mm:ssZ
        /// </summary>
        public DateTimeOffset StatusTimestamp { get; set; }

        /// <summary>
        /// Amount for the operation.
        /// </summary>
        public AmountData TotalAuthorizedAmount { get; set; }
    }
}
