/*
 * This file was automatically generated.
 */
namespace Worldline.Acquiring.Sdk.V1.Domain
{
    public class GetDCCRateRequest
    {
        public CardDataForDcc CardPaymentData { get; set; }

        /// <summary>
        /// A unique identifier of the operation, generated by the client.
        /// </summary>
        public string OperationId { get; set; }

        public PointOfSaleDataForDcc PointOfSaleData { get; set; }

        /// <summary>
        /// The reference of a previously used rate<br />
        /// This can be used in case of refund if you want to use the same rate
        /// as the original transaction.
        /// </summary>
        public string RateReferenceId { get; set; }

        /// <summary>
        /// The currency to convert to
        /// </summary>
        public string TargetCurrency { get; set; }

        public TransactionDataForDcc Transaction { get; set; }
    }
}
