/*
 * This file was automatically generated.
 */
namespace Worldline.Acquiring.Sdk.V1.Domain
{
    public class GetDccRateRequest
    {
        public CardDataForDcc CardPaymentData { get; set; }

        /// <summary>
        /// A globally unique identifier of the operation, generated by you.<br />
        /// We advise you to submit a UUID or an identifier composed of an arbitrary string
        /// and a UUID/URL-safe Base64 UUID (RFC 4648 §5).<br />
        /// It's used to detect duplicate requests or to reference an operation in
        /// technical reversals.
        /// </summary>
        public string OperationId { get; set; }

        public PointOfSaleDataForDcc PointOfSaleData { get; set; }

        /// <summary>
        /// The reference of a previously used rate<br />
        /// This can be used in case of refund if you want to use the same rate
        /// as the original transaction.
        /// </summary>
        public string RateReferenceId { get; set; }

        /// <summary>
        /// The currency to convert to
        /// </summary>
        public string TargetCurrency { get; set; }

        public TransactionDataForDcc Transaction { get; set; }
    }
}
