/*
 * This file was automatically generated.
 */
namespace Worldline.Acquiring.Sdk.V1.Domain
{
    public class OriginalTransactionReferences
    {
        /// <summary>
        /// ID assigned by the scheme to identify a transaction through
        /// its whole lifecycle.
        /// </summary>
        public string OriginalSchemeTransactionId { get; set; }

        /// <summary>
        /// A unique transaction identifier generated by Mastercard to provide consistent
        /// linking of related transaction activity throughout the transaction lifecycle.
        /// </summary>
        public string OriginalSchemeTransactionLinkId { get; set; }
    }
}
