/*
 * This file was automatically generated.
 */
namespace Worldline.Acquiring.Sdk.V1.Domain
{
    public class PaginationRequest
    {
        /// <summary>
        /// The index of the first item in the current page of search results.
        /// </summary>
        public int? FromIndex { get; set; }

        /// <summary>
        /// The number of items to be included in a page of search results.
        /// </summary>
        public int? PageSize { get; set; }

        /// <summary>
        /// A unique identifier for a search results.<br />
        /// It's used for pagination of search results and is generated by us.
        /// </summary>
        public string SearchId { get; set; }
    }
}
