/*
 * This file was automatically generated.
 */
namespace Worldline.Acquiring.Sdk.V1.Domain
{
    public class PaginationResponse
    {
        /// <summary>
        /// The index of the last item in the current page of search results.
        /// </summary>
        public int? LastIndex { get; set; }

        /// <summary>
        /// A unique identifier for a search results.<br />
        /// It's used for pagination of search results and is generated by us.
        /// </summary>
        public string SearchId { get; set; }

        /// <summary>
        /// The total number of items matching the search criteria.
        /// </summary>
        public int? TotalCount { get; set; }
    }
}
