/*
 * This file was automatically generated.
 */
using System;

namespace Worldline.Acquiring.Sdk.V1.Domain
{
    public class SubOperationForRefund
    {
        /// <summary>
        /// Amount for the operation.
        /// </summary>
        public AmountData Amount { get; set; }

        /// <summary>
        /// A globally unique identifier of the operation, generated by you.<br />
        /// We advise you to submit a UUID or an identifier composed of an arbitrary string
        /// and a UUID/URL-safe Base64 UUID (RFC 4648 §5).<br />
        /// It's used to detect duplicate requests or to reference an operation in
        /// technical reversals.
        /// </summary>
        public string OperationId { get; set; }

        /// <summary>
        /// Timestamp of the operation in ISO 8601 format (YYYY-MM-DDThh:mm:ss+TZD)<br />
        /// It can be expressed in merchant time zone (ex: 2023-10-10T08:00+02:00)
        /// or in UTC (ex: 2023-10-10T08:00Z)
        /// yyyy-MM-ddTHH:mm:ssZ
        /// </summary>
        public DateTimeOffset OperationTimestamp { get; set; }

        /// <summary>
        /// The kind of operation<br />
        /// Possible values are:
        /// <list type="bullet">
        ///   <item><description>AUTHORIZATION</description></item>
        ///   <item><description>CAPTURE</description></item>
        ///   <item><description>AUTHORIZATION_REVERSAL</description></item>
        /// </list>
        /// </summary>
        public string OperationType { get; set; }

        /// <summary>
        /// Numeric response code, e.g. 0, 5
        /// </summary>
        public string ResponseCode { get; set; }

        /// <summary>
        /// Category of response code.<br />
        /// Possible values are:
        /// <list type="bullet">
        ///   <item><description>APPROVED</description></item>
        ///   <item><description>PARTIALLY_APPROVED</description></item>
        ///   <item><description>DECLINED</description></item>
        /// </list>
        /// </summary>
        public string ResponseCodeCategory { get; set; }

        /// <summary>
        /// Description of the response code
        /// </summary>
        public string ResponseCodeDescription { get; set; }

        /// <summary>
        /// The duration to wait after the initial submission before retrying the operation.<br />
        /// Expressed using ISO 8601 duration format, ex: PT2H for 2 hours.<br />
        /// This field is only present when the operation can be retried later.<br />
        /// PT0 means that the operation can be retried immediately.
        /// </summary>
        public string RetryAfter { get; set; }
    }
}
