/*
 * This file was automatically generated.
 */
namespace Worldline.Acquiring.Sdk.V1.Domain
{
    public class SubsequentCardOnFileData
    {
        /// <summary>
        /// Card on file initiator
        /// </summary>
        public string CardOnFileInitiator { get; set; }

        /// <summary>
        /// ID assigned by the scheme to identify a transaction through
        /// its whole lifecycle.
        /// </summary>
        public string InitialSchemeTransactionId { get; set; }

        /// <summary>
        /// A unique transaction identifier generated by Mastercard to provide consistent
        /// linking of related transaction activity throughout the transaction lifecycle.
        /// </summary>
        public string InitialSchemeTransactionLinkId { get; set; }

        /// <summary>
        /// Transaction type
        /// </summary>
        public string TransactionType { get; set; }
    }
}
