/*
 * This file was automatically generated.
 */
namespace Worldline.Acquiring.Sdk.V1.Domain
{
    public class TransactionReferencesDispute : TransactionReferencesBase
    {
        /// <summary>
        /// The reference provided by the acquirer for the original transaction capture that resulted in the dispute.
        /// Only present if the acquirer provided a reference in the original transaction capture response.
        /// </summary>
        public string AcquirerTransactionReference { get; set; }

        /// <summary>
        /// The merchant's unique identifier for the original transaction capture request that resulted in the dispute.
        /// Only present if the merchant provided an <c>operationId</c> in the original transaction capture request.
        /// </summary>
        public string MerchantOperationId { get; set; }

        /// <summary>
        /// Retrieval reference number (RRN) for transaction
        /// </summary>
        public string RetrievalReferenceNumber { get; set; }

        /// <summary>
        /// ID assigned by the scheme to identify a transaction through
        /// its whole lifecycle.
        /// </summary>
        public string SchemeTransactionId { get; set; }

        /// <summary>
        /// A unique transaction identifier generated by Mastercard to provide consistent
        /// linking of related transaction activity throughout the transaction lifecycle.
        /// </summary>
        public string SchemeTransactionLinkId { get; set; }

        /// <summary>
        /// The identifier of the terminal
        /// </summary>
        public string TerminalId { get; set; }

        /// <summary>
        /// The reference of the transaction from the terminal used in the original transaction capture that resulted
        /// in the dispute.
        /// </summary>
        public string TerminalTransactionReference { get; set; }
    }
}
